### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by sslash** [michaelcontento/redux-storage-merger-immutablejs#15]
How do you use the merger with redux-storage?

**Comment by boobooninja** [comment]
+1

**Comment by boobooninja** [comment]
digging through code I found this:
https://github.com/michaelcontento/redux-storage/blob/master/src/reducer.js

looks like the merger can be passed to the storage.reducer function.

`
import immutableMerger from 'redux-storage-merger-immutablejs';
const reducer = storage.reducer(rootReducer, immutableMerger);
`

**Comment by sslash** [comment]
Nice!! Thanks

**Comment by michaelcontento** [comment]
Added to the README in 7125950b28816e04cff0d1717058249f8d28106c
